/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestRouteImport } from './routes/test/route'
import { Route as IndexImport } from './routes/index'
import { Route as TestAppImport } from './routes/test/app'

// Create/Update Routes

const TestRouteRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TestAppRoute = TestAppImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => TestRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRoute
    }
    '/test/app': {
      id: '/test/app'
      path: '/app'
      fullPath: '/test/app'
      preLoaderRoute: typeof TestAppImport
      parentRoute: typeof TestRouteImport
    }
  }
}

// Create and export the route tree

interface TestRouteRouteChildren {
  TestAppRoute: typeof TestAppRoute
}

const TestRouteRouteChildren: TestRouteRouteChildren = {
  TestAppRoute: TestAppRoute,
}

const TestRouteRouteWithChildren = TestRouteRoute._addFileChildren(
  TestRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test': typeof TestRouteRouteWithChildren
  '/test/app': typeof TestAppRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof TestRouteRouteWithChildren
  '/test/app': typeof TestAppRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/test': typeof TestRouteRouteWithChildren
  '/test/app': typeof TestAppRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test' | '/test/app'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test' | '/test/app'
  id: '__root__' | '/' | '/test' | '/test/app'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestRouteRoute: typeof TestRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestRouteRoute: TestRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/test"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/test": {
      "filePath": "test/route.tsx",
      "children": [
        "/test/app"
      ]
    },
    "/test/app": {
      "filePath": "test/app.tsx",
      "parent": "/test"
    }
  }
}
ROUTE_MANIFEST_END */
