[workspace]
members = [
  "packages/*",
]
resolver = "3"

[workspace.package]
authors = [
  "Polyfrost",
  "Polyfrost Contributors",
]
documentation = "https://github.com/Polyfrost/OneLauncher"
edition = "2024"
homepage = "https://polyfrost.org/projects/oneclient"
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://github.com/Polyfrost/OneLauncher"
rust-version = "1.97"
version = "2.6.0"

[workspace.dependencies]
# core
oneclient_auth = {path = "./packages/oneclient_auth"}
oneclient_cluster = {path = "./packages/oneclient_cluster"}
oneclient_common = {path = "./packages/oneclient_common"}
oneclient_content = {path = "./packages/oneclient_content"}
oneclient_core = {path = "./packages/oneclient_core"}
oneclient_db = {path = "./packages/oneclient_db"}
oneclient_discord = {path = "./packages/oneclient_discord"}
oneclient_events = {path = "./packages/oneclient_events"}
oneclient_java = {path = "./packages/oneclient_java"}
oneclient_macro = {path = "./packages/oneclient_macro"}
oneclient_mc = {path = "./packages/oneclient_mc"}
oneclient_net = {path = "./packages/oneclient_net"}
oneclient_polyplus = {path = "./packages/oneclient_polyplus"}
polyio = {path = "./packages/polyio"}

# core (extra)
discord-rich-presence = {version = "=1.1.0"}
interfrost = {version = "=1.5.0"}

# logging
sentry = {version = "=0.49.3", default-features = false, features = [
  "backtrace",
  "contexts",
  "debug-images",
  "panic",
  "release-health",
  "reqwest",
  "rustls",
]}
sentry-tracing = {version = "=0.49.3"}
tracing = {version = "=0.1.44"}
tracing-futures = {version = "=0.2.5"}
tracing-subscriber = {version = "=0.3.23", features = ["env-filter", "fmt", "ansi", "json", "parking_lot", "registry"]}

# database
sqlx = {version = "=0.9.0", default-features = false, features = [
  "runtime-tokio",
  "tls-rustls-ring-native-roots",
  "sqlite",
  "derive",
  "macros",
  "migrate",
  "json",
  "uuid",
  "chrono",
]}

# async
astral-tokio-tar = {version = "=0.7.0"}
async-compression = {version = "=0.4.48", features = ["tokio", "gzip"]}
async-stream = {version = "=0.3.6"}
async-tempfile = {version = "=0.8.0", features = ["uuid"]}
async-trait = {version = "=0.1.92"}
async_zip = {version = "=0.0.19", features = ["tracing", "chrono", "tokio", "tokio-fs", "deflate", "deflate64"]}
futures-lite = {version = "=2.6.1"}
futures-util = {version = "=0.3.34", features = ["tokio-io"]}
reqwest = {version = "=0.13.5", default-features = false, features = [
  "json",
  "stream",
  "multipart",
  "blocking",
  "rustls",
  "charset",
  "http2",
  "deflate",
  "gzip",
  "brotli",
  "form",
  "system-proxy",
]}
reqwest-websocket = {version = "=0.6.0"}
tokio = {version = "=1.53.1", features = ["full"]}
tokio-stream = {version = "=0.1.19", features = ["full"]}
tokio-util = {version = "=0.7.19", features = ["full"]}

# crypto (content hashing)
byteorder = {version = "=1.5.0"}
digest = {version = "=0.11.3"}
md-5 = {version = "=0.11.0", default-features = false}
p256 = {version = "=0.14.0", features = ["ecdsa", "pkcs8"]}
sha1 = {version = "=0.11.0", default-features = false}
sha2 = {version = "=0.11.0", default-features = false}

# util
arboard = {version = "=3.6.1", features = ["wayland-data-control"]}
arc-swap = {version = "=1.9.2"}
base64 = {version = "=0.23.1"}
bytes = {version = "=1.12.1"}
chrono = {version = "=0.4.45", features = ["serde"]}
directories = {version = "=6.0.0"}
dunce = {version = "=1.0.5"}
htmd = {version = "=0.5.5"}
indicatif = {version = "=0.18.6", features = ["tokio"]}
junction = {version = "=2.1.0"}
libc = {version = "=0.2.189"}
notify = {version = "=8.2.0"}
open = {version = "=5.4.4", features = ["shellexecute-on-windows"]}
parking_lot = {version = "=0.12.5"}
pulldown-cmark = {version = "=0.13.4", default-features = false}
rand = {version = "=0.10.3"}
regex = {version = "=1.13.1"}
rfd = {version = "=0.17.2"}
rust-embed = {version = "=8.12.0", features = ["include-exclude", "compression", "debug-embed"]}
sanitize-filename = {version = "=0.6.0"}
serde = {version = "=1.0.229"}
serde_json = {version = "=1.0.151"}
serde_repr = {version = "=0.1.21"}
sysinfo = {version = "=0.39.6"}
toml = {version = "=1.1.6", default-features = false, features = ["parse", "serde"]}
trash = {version = "=5.2.9"}
percent-encoding = {version = "=2.3.2"}
url = {version = "=2.5.8", features = ["serde"]}
uuid = {version = "=1.26.1", features = ["serde", "v4"]}
windows-sys = {version = "=0.61.2", features = ["Win32_Foundation", "Win32_Storage_FileSystem"]}

# util (codegen/macro)
anyhow = {version = "=1.0.104"}
proc-macro2 = {version = "=1.0.107"}
quote = {version = "=1.0.47"}
strum = {version = "=0.28.0", features = ["derive"]}
syn = {version = "=3.0.6"}
thiserror = {version = "=2.0.21"}

# ui
freya = {git = "https://github.com/Polyfrost/freya", rev = "2e4a11ec569d72ef1a809e9365548daa3cc5f6b5", features = ["engine", "winit", "router", "remote-asset", "sdk-tokio", "query", "radio", "borderless", "titlebar", "tray", "metrics"]}
freya-core = {git = "https://github.com/Polyfrost/freya", rev = "2e4a11ec569d72ef1a809e9365548daa3cc5f6b5",}
freya-testing = {git = "https://github.com/Polyfrost/freya", rev = "2e4a11ec569d72ef1a809e9365548daa3cc5f6b5",}
freya-skia-safe = "=0.100.0-beta.1" # required for the SKSL player renderer
image = {version = "=0.25.10", default-features = false, features = ["png", "jpeg"]}

[profile.release]
codegen-units = 1
debug = "line-tables-only"
lto = "fat"
opt-level = 3
panic = "abort"
split-debuginfo = "packed"
strip = true

[profile.release-profiling]
inherits = "release"

debug = true
strip = false

[profile.release-fastprofiling]
inherits = "release"

codegen-units = 16
debug = true
lto = false
strip = false
