packages:
  - apps/oneclient/*
  - apps/onelauncher/*
  - packages/*
  - .github/actions/*

catalog:
  # --
  #  dev dependencies
  # ---

  # typescript
  tsx: ^4.19.4
  typescript: ^5.8.3
  '@types/node': ^22.13.14
  '@types/react': ^19.0.8
  '@types/react-dom': ^19.0.3

  # eslintjs
  eslint: ^9.20.0
  '@flowr/eslint': ^6.0.0
  '@eslint-react/eslint-plugin': ^1.48.5
  '@tanstack/eslint-config': ^0.1.0

  # vite
  vite: ^6.3.4
  vite-plugin-dts: ^4.5.4
  vite-plugin-static-copy: ^3.0.0
  vite-plugin-svgr: ^4.3.0
  '@vitejs/plugin-react': ^4.3.4
  '@tailwindcss/vite': ^4.0.6

  # other
  rimraf: ^6.0.1

  # ---
  #  dependencies
  # ---

  # react + libraries
  react: ^19.0.0
  react-aria-components: ^1.8.0
  '@tanstack/react-query': ^5.66.5
  '@tanstack/react-router': ^1.114.3
  '@untitled-theme/icons-react': ^0.14.0
  motion: ^12.10.5
  react-dom: ^19.0.0

  # tailwindcss
  tailwind-merge: ^3.2.0
  tailwind-variants: ^1.0.0
  tailwindcss: ^4.0.6
  tailwindcss-animated: ^2.0.0
  tailwindcss-react-aria-components: ^2.0.0

  # tanstack
  '@tanstack/match-sorter-utils': ^8.19.4
  '@tanstack/react-query-devtools': ^5.66.5
  '@tanstack/react-router-devtools': ^1.114.3
  '@tanstack/react-table': ^8.21.2
  '@tanstack/router-plugin': ^1.114.3

  # tauri
  taurpc: ^1.8.1
  '@tauri-apps/api': ^2.5.0
  '@tauri-apps/plugin-clipboard-manager': ^2.2.2
  '@tauri-apps/plugin-dialog': ^2.2.1
  '@tauri-apps/plugin-shell': ^2.2.1
  '@tauri-apps/plugin-opener': ^2.3.0

  # other
  overlayscrollbars: ^2.11.2
  overlayscrollbars-react: ^0.5.6
  '@fontsource/poppins': ^5.2.6
  '@formatjs/intl-durationformat': ^0.7.4
  zustand: ^5.0.5
  valtio: ^2.1.5
