[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-refresh-client-manager",
  "allow-launch-cluster",
  "allow-create-cluster",
  "allow-get-clusters",
  "allow-get-cluster",
  "allow-get-cluster-logs",
  "allow-get-cluster-log",
  "allow-get-manifest",
  "allow-login-msa",
]
