name: Enhancement
description: Suggest an enhancement for an existing feature
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: Before raising an issue, please search for existing issues and [Discord](https://polyfrost.org/discord) suggestions to avoid creating duplicates.
  - type: input
    attributes:
      label: Original reporter/ticket ID
      description: If you are rewording a ticket, put the original reporter(s) and ticket ID(s). If not, leave this blank.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Project
      description: Select the project this issue is related to.
      multiple: true
      default: General
      options:
        - General
        - Core
        - OneClient
        - OneLauncher
  - type: textarea
    attributes:
      label: Is your suggested enhancement related to a problem? Please describe, or link another Issue.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the suggested enhancement here.
    validations:
      required: false
