[package]
name = "onelauncher_prisma"
description = "prisma client for onelauncher"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
readme = { workspace = true }
homepage = { workspace = true }
authors = { workspace = true }

[dependencies]
prisma-client-rust = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
