//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "cluster_bundle_overrides")]
#[serde(rename = "ClusterBundleOverridesModel")]
#[onelauncher_macro::specta]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = true)]
	pub id: i64,
	pub cluster_id: i64,
	pub bundle_name: String,
	pub package_id: String,
	pub override_type: OverrideType,
}

#[derive(Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
#[onelauncher_macro::specta]
pub enum OverrideType {
	#[sea_orm(string_value = "Removed")]
	Removed,
	#[sea_orm(string_value = "Disabled")]
	Disabled,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::clusters::Entity",
		from = "Column::ClusterId",
		to = "super::clusters::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Clusters,
}

impl Related<super::clusters::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Clusters.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
