//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

pub mod entity {
	pub use crate::cluster_bundle_overrides::Entity as ClusterBundleOverrides;
	pub use crate::cluster_groups::Entity as ClusterGroups;
	pub use crate::cluster_packages::Entity as ClusterPackages;
	pub use crate::clusters::Entity as Clusters;
	pub use crate::java_versions::Entity as JavaVersions;
	pub use crate::packages::Entity as Packages;
	pub use crate::setting_profiles::Entity as SettingProfiles;
}

pub mod model {
	pub use crate::cluster_bundle_overrides::{
		ActiveModel as ClusterBundleOverridePartial, Model as ClusterBundleOverride,
	};
	pub use crate::cluster_groups::Model as ClusterGroup;
	pub use crate::cluster_packages::Model as ClusterPackage;
	pub use crate::clusters::Model as Cluster;
	pub use crate::java_versions::Model as JavaVersion;
	pub use crate::packages::Model as Package;
	pub use crate::setting_profiles::Model as SettingsProfile;

	pub use crate::cluster_groups::ActiveModel as ClusterGroupPartial;
	pub use crate::cluster_packages::ActiveModel as ClusterPackagePartial;
	pub use crate::clusters::ActiveModel as ClusterPartial;
	pub use crate::java_versions::ActiveModel as JavaVersionPartial;
	pub use crate::packages::ActiveModel as PackagePartial;
	pub use crate::setting_profiles::ActiveModel as SettingsProfilePartial;
}
