//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

pub use super::cluster_groups::Entity as ClusterGroups;
pub use super::clusters::Entity as Clusters;
pub use super::java_versions::Entity as JavaVersions;
pub use super::packages::Entity as Packages;
pub use super::setting_profiles::Entity as SettingProfiles;
