[package]
name = "onelauncher_macro"
description = "Macros for OneLauncher"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
readme = { workspace = true }
homepage = { workspace = true }
authors = { workspace = true }

[lib]
name = "onelauncher_macro"
path = "src/lib.rs"
proc-macro = true

[features]
default = []
specta = []

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
