name: Setup Pnpm
description: Setup Pnpm
inputs:
  token:
    description: GitHub token
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@ac5bf11548bf5e19b8aadb8182072616590fa4a6

    - name: Install Node.js
      uses: actions/setup-node@26961cf329f22f6837d5f54c3efd76b480300ace
      with:
        token: ${{ inputs.token }}
        check-latest: true
        node-version-file: .nvmrc
        cache: pnpm

    - name: Install dependencies
      shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
      env:
        NODE_ENV: debug
        GITHUB_TOKEN: ${{ inputs.token }}
      run: pnpm install --frozen-lockfile
