[package]
name = "onelauncher_new"
description = "The core of OneLauncher"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
readme = { workspace = true }
homepage = { workspace = true }
authors = { workspace = true }

[lib]
path = "src/lib.rs"

[features]
default = [ "cli" ]
tauri = [
	"dep:tauri",
	"dep:tauri-specta",
	"specta",
	"gui"
]
specta = [ "dep:specta" ]
cli = [ "dep:indicatif" ]
gui = []

[lints]
workspace = true

[dependencies]
interpulse = { workspace = true }

# logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-error = { workspace = true }
tracing-appender = { workspace = true }

# serialization
serde = { workspace = true }
serde_json = { workspace = true }
serde_ini = { workspace = true }
serde_repr = { workspace = true }
serde_with = { workspace = true }

# utils
sqlx = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }
regex = { workspace = true }
sysinfo = { workspace = true }
whoami = { workspace = true }
lazy_static = { workspace = true }
rand = { workspace = true }
url = { workspace = true }
async-trait = { workspace = true }

# integration
discord-rich-presence = { workspace = true }

# crypto
sha1_smol = { workspace = true }
sha2 = { workspace = true }
murmur2 = { workspace = true }
md5 = { workspace = true }

# io
zip = { workspace = true }
async_zip = { workspace = true }
dirs = { workspace = true }
bytes = { workspace = true }
base64 = { workspace = true }
async-compression = { workspace = true }
dunce = { workspace = true }

# features[tauri]
tauri = { workspace = true, optional = true }
tauri-specta = { workspace = true, optional = true }

# features[specta]
specta = { workspace = true, optional = true }

# features[cli]
indicatif = { workspace = true, optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
onelauncher_gamemode = { workspace = true }
